### ISSUE TITLE
Firefox only: useDragAndDrop breaks input selection

### ISSUE THREAD

**Issue by vmihailenco** [formkit/drag-and-drop#110]
Reproduction (requires Firefox): https://codesandbox.io/p/sandbox/drag-ndrop-kit-forked-83wtw7?file=%2Fsrc%2FApp.tsx%3A1%2C10-1%2C24

1. Open the example in Firefox
2. Try to select the text in the input
3. Observe that the text can't be selected

Here is how it works in Chrome

[drag-ndrop-kit (forked) - CodeSandbox.webm](https://github.com/user-attachments/assets/cc5e8bbc-73a6-4872-afc4-8a736c1fb516)

The same does not work in Firefox, i.e. text can't be selected

**Comment by sashamilenkovic** [comment]
@vmihailenco Appreciate the reproduction. Will take a look.

**Comment by Min-lg** [comment]
i want to fix it

**Comment by sashamilenkovic** [comment]
@vmihailenco Haven't had the chance yet. I believe the issue involves how Firefox handles the draggable attribute. This is top priority but no update yet.

**Comment by EdeMeijer** [comment]
Hey I ran into the same issue, hope you can find out what's causing it

**Comment by sashamilenkovic** [comment]
Fix for this is implemented, will be released in the next few days

**Comment by EdeMeijer** [comment]
Hi, any updates on this? Seems like it still broken in the latest version.

**Comment by sashamilenkovic** [comment]
@EdeMeijer fix will be included in the next minor release. Hoping to have that published soon

**Comment by sashamilenkovic** [comment]
Hey everyone! Apologies for the delay. This should be resolved at v0.3.0

**Comment by sashamilenkovic** [comment]
Whoops, this should now be resolved at v0.3.1. Please ping me if you're still having issues.

**Comment by EdeMeijer** [comment]
Hey, I upgraded to v0.3.2 but the issue still remains. I forked the original codesandbox example of @vmihailenco and upgraded the package there as well, and that repro also remains broken. https://codesandbox.io/p/sandbox/drag-ndrop-kit-forked-ygt5fr

Please assist.

**Comment by sashamilenkovic** [comment]
@EdeMeijer Ah, you are right. Seems to still be broken if drag handles are used (if you remove from the sandbox it seems to be working).

**Comment by sashamilenkovic** [comment]
@EdeMeijer Try this again on v0.3.3. Should be working fine now, whether using drag handles or not. Thank you for following up on this.

**Comment by EdeMeijer** [comment]
Can confirm that it's working as expected now, thank you!
