### ISSUE TITLE
Inconsistent useState updates in custom plugins.

### ISSUE THREAD

**Issue by suspiciousRaccoon** [formkit/drag-and-drop#24]
I'm trying to replicate the behavior of the example in [custom plugins](https://drag-and-drop.formkit.com/#custom-plugin) but for some reason `dragCount` never goes above 2. `dragStatus` updates correctly 
Example in [CodeSandbox](https://codesandbox.io/p/github/suspiciousRaccoon/formkit-drag-and-drop-inconsistent-state-updates/main?import=true).
```js
import React from "react";
import { useState } from "react";
import { useDragAndDrop } from "@formkit/drag-and-drop/react";
import { parents } from "@formkit/drag-and-drop";
import "./App.css";

function App() {
  const [dragStatus, setDragStatus] = useState("Not dragging");
  const [dragCount, setDragCount] = useState(0);
  const dragStatusPlugin = (parent) => {
    const parentData = parents.get(parent);
    if (!parentData) return;

    function dragstart(event) {
      const node = event.target;
      setDragStatus(`Dragging ${node.textContent}`);
      setDragCount(dragCount + 1);
    }

    function dragend() {
      setDragStatus("Not dragging");
    }

    return {
      setup() {},
      teardown() {},
      setupNode(data) {
        data.node.addEventListener("dragstart", dragstart);
        data.node.addEventListener("dragend", dragend);
      },
      tearDownNode(data) {
        data.node.removeEventListener("drastart", dragstart);
        data.node.removeEventListener("dragend", dragend);
      },
      setupNodeRemap(data) {},
      tearDownNodeRemap(data) {},
    };
  };
  const [parent, items] = useDragAndDrop(
    ["🍦 vanilla", "🍫 chocolate", "🍓 strawberry"],
    { plugins: [dragStatusPlugin] }
  );
  return (
    <div>
      <strong>Rank your favorite flavors</strong>
      <br />
      <span>{dragStatus}</span>
      <br />
      <span>{dragCount}</span>
      <ul ref={parent}>
        {items.map((item) => {
          return <li key={item}>{item}</li>;
        })}
      </ul>
    </div>
  );
}

export default App;
```

**Comment by sashamilenkovic** [comment]
@suspiciousRaccoon This should be resolved at v0.0.24. Let me know if you have any other issues (appreciate you taking the time to file these issues).

**Comment by suspiciousRaccoon** [comment]
@sashamilenkovic I've tried the new version and the demo still doesn't work as the one in the docs. The number doesn't update if you try to drag the same element multiple times. You need to first order them for it to update, and this ordering also doesn't update the number. Once it gets "stuck" dragging any of the elements won't update the counter. I'm using the same example in the same repo, I only updated the drag and drop to the latest version.
Example in [CodeSandbox](https://codesandbox.io/p/github/suspiciousRaccoon/formkit-drag-and-drop-inconsistent-state-updates/main?import=true).

**Comment by sashamilenkovic** [comment]
@suspiciousRaccoon You're right, will look into this tomorrow. Apologies (I'm personally still very new with React). Thank you for your patience.

**Comment by suspiciousRaccoon** [comment]
Hey, I tried the new version and it still isn't 1:1 with the docs example. I recorded a video to better showcase the differences.


https://github.com/formkit/drag-and-drop/assets/127566947/f652d3fe-17ef-4d5b-b146-17f971501f14




I tried accessing your CodeSandbox but the link was private. Here is a [CodeSandbox](https://codesandbox.io/p/github/suspiciousRaccoon/formkit-drag-and-drop-inconsistent-state-updates/main?import=true) with the same example but with the updated dep. If there's some logging or something I could do to help resolve this issue please let me know.

**Comment by sashamilenkovic** [comment]
@suspiciousRaccoon The link is private? Hmmm, I seem to be able to access it in a private window as well. In any case,

```import React from "react";
import { useState } from "react";
import { useDragAndDrop } from "@formkit/drag-and-drop/react";
import { parents, addEvents } from "@formkit/drag-and-drop";
import "./App.css";

function App() {
  const [dragStatus, setDragStatus] = useState("Not dragging");
  const [dragCount, setDragCount] = useState(0);

  const dragStatusPlugin = (parent) => {
    const parentData = parents.get(parent);
    if (!parentData) return;

    function dragstart(event) {
      const node = event.target;
      setDragStatus(`Dragging ${node.textContent}`);
      setDragCount((count) => count + 1);
    }

    function dragend() {
      setDragStatus("Not dragging");
    }

    return {
      setup() {},
      teardown() {},
      setupNode(data) {
        data.nodeData.abortControllers.customPlugin = addEvents(data.node, {
          dragstart: dragstart,
          dragend: dragend,
        });
      },
      tearDownNode(data) {
        if (data.nodeData?.abortControllers?.customPlugin) {
          data.nodeData?.abortControllers?.customPlugin.abort();
        }
      },
      setupNodeRemap() {},
      tearDownNodeRemap() {},
    };
  };
  const [parent, items] = useDragAndDrop(
    ["🍦 vanilla", "🍫 chocolate", "🍓 strawberry"],
    { plugins: [dragStatusPlugin] }
  );
  return (
    <div>
      <strong>Rank your favorite flavors</strong>
      <br />
      <span>{dragStatus}</span>
      <br />
      <span>{dragCount}</span>
      <ul ref={parent}>
        {items.map((item) => {
          return <li key={item}>{item}</li>;
        })}
      </ul>
    </div>
  );
}

export default App;
```

Here is the updated code for React (which is also on the docs). Some key differences include the way state is being updated as well as the way event listeners are being added and removed.

**Comment by suspiciousRaccoon** [comment]
For some reason I had to open a private window to access the CodeSandbox. In any case, it seems to be working correctly! I'll close the issue now, thanks for all the work you've put into this lib!

**Comment by sashamilenkovic** [comment]
@suspiciousRaccoon Appreciate the feedback and the patience to get this resolved!
