### ISSUE TITLE
Dragged elements overflow the root

### ISSUE THREAD

**Issue by wesharper** [formkit/drag-and-drop#35]
This can cause weird behavior on responsive sites. For instance, the fixed header in my site grows horizontally until the items on the right side can no longer be seen. It's also accentuated when working in horizontally large lists of tabular data where the dragged element is particularly long.

https://github.com/formkit/drag-and-drop/assets/13283469/69fef5c8-08c0-4171-bf06-d3d6a3f01e54

**Comment by sashamilenkovic** [comment]
@wesharper This should be resolved at v0.0.32

**Comment by hungify** [comment]
Hey, @sashamilenkovic!
![CleanShot 2024-12-20 at 23 16 23](https://github.com/user-attachments/assets/937744a9-7cda-4b57-a9a7-4de625a9422b)

The issue persists in version 0.2.6 across Chrome, Firefox, Brave, iOS, and Android.

**Comment by justin-schroeder** [comment]
Closing as resolved by architecture: the synthetic drag preview is now rendered as a top-layer `popover` element rather than an absolutely-positioned node in the document flow, so it can no longer expand the page's scrollable area, and auto-scroll is clamped to the page's original scroll bounds. That addresses both the original report and the v0.2.6 recurrence. If overflow still happens on a current release, please open a fresh issue with a repro. 🙏
